export const mockData = [
  {
    id: 1,
    expense_title: 'Voya International High Dividend Equity Income Fund',
    expense_category: 'Shoes',
    expense_value: '$52939.84',
    expense_owner: 'Catie',
    expense_frequency: 'Once',
    date: '5/6/2021',
    icon: "shoe-sneaker",
    time: '12:33 AM',
  },
  {
    id: 2,
    expense_title: 'OpGen, Inc.',
    expense_category: 'Automotive',
    expense_value: '$70884.24',
    expense_owner: 'Stormie',
    expense_frequency: 'Daily',
    date: '24/12/2021',
    icon: "car",
    time: '12:23 AM',
  },
  {
    id: 3,
    expense_title: 'Boise Cascade, L.L.C.',
    expense_category: 'Automotive',
    expense_value: '$74695.25',
    expense_owner: 'Rosita',
    expense_frequency: 'Often',
    date: '20/8/2021',
    icon: "car",
    time: '11:41 PM',
  },
  {
    id: 4,
    expense_title: 'CHS Inc',
    expense_category: 'Clothing',
    expense_value: '$24316.97',
    expense_owner: 'Franky',
    expense_frequency: 'Seldom',
    date: '30/7/2021',
    icon: "hanger",
    time: '7:39 PM',
  },
  {
    id: 5,
    expense_title: 'Landmark Infrastructure Partners LP',
    expense_category: 'Tools',
    expense_value: '$96101.65',
    expense_owner: 'Reginald',
    expense_frequency: 'Never',
    date: '26/7/2021',
    icon: "tools",
    time: '11:47 AM',
  },
  {
    id: 6,
    expense_title: 'BanColombia S.A.',
    expense_category: 'Jewelry',
    expense_value: '$12614.15',
    expense_owner: 'Garth',
    expense_frequency: 'Once',
    date: '18/5/2021',
    icon: "diamond-stone",
    time: '2:39 PM',
  },
  {
    id: 7,
    expense_title: 'Gulf Island Fabrication, Inc.',
    expense_category: 'Kids',
    expense_value: '$54109.20',
    expense_owner: 'Brenn',
    expense_frequency: 'Often',
    date: '11/9/2021',
    icon: "teddy-bear",
    time: '4:39 AM',
  },
  {
    id: 8,
    expense_title: 'Axis Capital Holdings Limited',
    expense_category: 'Grocery',
    expense_value: '$19665.53',
    expense_owner: 'Purcell',
    expense_frequency: 'Weekly',
    date: '26/6/2021',
    icon: "cart",
    time: '4:44 AM',
  },
  {
    id: 9,
    expense_title: 'Zendesk, Inc.',
    expense_category: 'Grocery',
    expense_value: '$34010.91',
    expense_owner: 'Correy',
    expense_frequency: 'Often',
    date: '26/10/2021',
    icon: "cart",
    time: '3:21 PM',
  },
  {
    id: 10,
    expense_title: 'MFS Government Markets Income Trust',
    expense_category: 'Grocery',
    expense_value: '$68734.51',
    expense_owner: 'Hamid',
    expense_frequency: 'Weekly',
    date: '16/5/2021',
    icon: "cart",
    time: '1:07 PM',
  },
  {
    id: 11,
    expense_title: 'Activision Blizzard, Inc',
    expense_category: 'Games',
    expense_value: '$44031.92',
    expense_owner: 'Rey',
    expense_frequency: 'Monthly',
    date: '16/11/2021',
    icon: "gamepad-outline",
    time: '3:31 PM',
  },
  {
    id: 12,
    expense_title: 'Great Lakes Dredge & Dock Corporation',
    expense_category: 'Clothing',
    expense_value: '$92864.79',
    expense_owner: 'Tony',
    expense_frequency: 'Daily',
    date: '12/2/2022',
    icon: "hanger",
    time: '11:22 AM',
  },
  {
    id: 13,
    expense_title: 'AirMedia Group Inc',
    expense_category: 'Electronics',
    expense_value: '$65102.28',
    expense_owner: 'Cyb',
    expense_frequency: 'Once',
    date: '7/1/2022',
    icon: "devices",
    time: '2:16 PM',
  },
  {
    id: 14,
    expense_title: 'Inspired Entertainment, Inc.',
    expense_category: 'Beauty',
    expense_value: '$45234.10',
    expense_owner: 'Erin',
    expense_frequency: 'Yearly',
    date: '13/8/2021',
    icon: "lipstick",
    time: '10:24 AM',
  },
  {
    id: 15,
    expense_title: 'Moneygram International, Inc.',
    expense_category: 'Shoes',
    expense_value: '$68805.81',
    expense_owner: 'Ardelis',
    expense_frequency: 'Once',
    date: '16/5/2021',
    icon: "shoe-sneaker",
    time: '9:31 PM',
  },
  {
    id: 16,
    expense_title: 'Capital One Financial Corporation',
    expense_category: 'Garden',
    expense_value: '$15854.52',
    expense_owner: 'Georgianne',
    expense_frequency: 'Often',
    date: '1/7/2021',
    icon: "sprout",
    time: '8:05 AM',
  },
  {
    id: 17,
    expense_title: 'PolarityTE, Inc.',
    expense_category: 'Books',
    expense_value: '$97459.27',
    expense_owner: 'Lavinia',
    expense_frequency: 'Never',
    date: '6/9/2021',
    icon: "book-open-page-variant",
    time: '8:28 AM',
  },
  {
    id: 18,
    expense_title: 'Aberdeen Japan Equity Fund, Inc. ',
    expense_category: 'Jewelry',
    expense_value: '$99628.50',
    expense_owner: 'Dredi',
    expense_frequency: 'Daily',
    date: '3/8/2021',
    icon: "diamond-stone",
    time: '3:44 AM',
  },
  {
    id: 19,
    expense_title: 'AmerisourceBergen Corporation (Holding Co)',
    expense_category: 'Sports',
    expense_value: '$72171.46',
    expense_owner: 'Lon',
    expense_frequency: 'Daily',
    date: '20/8/2021',
    icon: "basketball",
    time: '6:45 AM',
  },
  {
    id: 20,
    expense_title: 'Maximus, Inc.',
    expense_category: 'Movies',
    expense_value: '$43002.30',
    expense_owner: 'Renault',
    expense_frequency: 'Seldom',
    date: '27/7/2021',
    icon: "movie-roll",
    time: '1:19 PM',
  },
  {
    id: 21,
    expense_title: 'Ikonics Corporation',
    expense_category: 'Clothing',
    expense_value: '$93085.53',
    expense_owner: 'Arnaldo',
    expense_frequency: 'Monthly',
    date: '5/8/2021',
    icon: "hanger",
    time: '12:45 AM',
  },
  {
    id: 22,
    expense_title: 'Mizuho Financial Group, Inc.',
    expense_category: 'Outdoors',
    expense_value: '$35602.48',
    expense_owner: 'Violetta',
    expense_frequency: 'Monthly',
    date: '15/12/2021',
    icon: "tent",
    time: '5:53 PM',
  },
  {
    id: 23,
    expense_title: 'iPath US Treasury 5-year Bear ETN',
    expense_category: 'Computers',
    expense_value: '$68702.15',
    expense_owner: 'Antony',
    expense_frequency: 'Monthly',
    date: '2/8/2021',
    icon: "laptop",
    time: '3:31 AM',
  },
  {
    id: 24,
    expense_title: 'ADOMANI, Inc.',
    expense_category: 'Electronics',
    expense_value: '$7448.00',
    expense_owner: 'Nev',
    expense_frequency: 'Often',
    date: '26/3/2021',
    icon: "devices",
    time: '12:09 PM',
  },
  {
    id: 25,
    expense_title: 'Veeva Systems Inc.',
    expense_category: 'Computers',
    expense_value: '$31686.27',
    expense_owner: 'Caddric',
    expense_frequency: 'Yearly',
    date: '4/11/2021',
    icon: "laptop",
    time: '12:56 AM',
  },
  {
    id: 26,
    expense_title: 'Keane Group, Inc.',
    expense_category: 'Sports',
    expense_value: '$64864.90',
    expense_owner: 'Esra',
    expense_frequency: 'Monthly',
    date: '17/1/2022',
    icon: "basketball",
    time: '12:51 AM',
  },
  {
    id: 27,
    expense_title: 'Coffee Holding Co., Inc.',
    expense_category: 'Sports',
    expense_value: '$88576.75',
    expense_owner: 'Lorens',
    expense_frequency: 'Never',
    date: '27/8/2021',
    icon: "basketball",
    time: '5:51 PM',
  },
  {
    id: 28,
    expense_title: 'HSBC Holdings plc',
    expense_category: 'Grocery',
    expense_value: '$51028.43',
    expense_owner: 'Sophey',
    expense_frequency: 'Monthly',
    date: '24/3/2021',
    icon: "cart",
    time: '8:35 AM',
  },
  {
    id: 29,
    expense_title: 'Vulcan Materials Company',
    expense_category: 'Music',
    expense_value: '$37301.54',
    expense_owner: 'Barbette',
    expense_frequency: 'Once',
    date: '5/7/2021',
    icon: "music-clef-treble",
    time: '1:57 PM',
  },
  {
    id: 30,
    expense_title: 'Celgene Corporation',
    expense_category: 'Sports',
    expense_value: '$29953.50',
    expense_owner: 'Manuel',
    expense_frequency: 'Yearly',
    date: '19/7/2021',
    icon: "basketball",
    time: '11:14 PM',
  },
  {
    id: 31,
    expense_title: 'BiondVax Pharmaceuticals Ltd.',
    expense_category: 'Jewelry',
    expense_value: '$1268.97',
    expense_owner: 'Camel',
    expense_frequency: 'Often',
    date: '7/4/2021',
    icon: "diamond-stone",
    time: '4:20 PM',
  },
  {
    id: 32,
    expense_title: 'Global Blood Therapeutics, Inc.',
    expense_category: 'Toys',
    expense_value: '$84350.62',
    expense_owner: 'Duffie',
    expense_frequency: 'Yearly',
    date: '12/8/2021',
    icon: "pinwheel",
    time: '3:43 PM',
  },
  {
    id: 33,
    expense_title: 'Validea Market Legends ETF',
    expense_category: 'Beauty',
    expense_value: '$38380.08',
    expense_owner: 'Robinetta',
    expense_frequency: 'Daily',
    date: '23/6/2021',
    icon: "lipstick",
    time: '9:24 PM',
  },
  {
    id: 34,
    expense_title: 'Acxiom Corporation',
    expense_category: 'Books',
    expense_value: '$44966.13',
    expense_owner: 'Juli',
    expense_frequency: 'Seldom',
    date: '30/4/2021',
    icon: "book-open-page-variant",
    time: '7:46 AM',
  },
  {
    id: 35,
    expense_title: 'Carvana Co.',
    expense_category: 'Beauty',
    expense_value: '$81269.47',
    expense_owner: 'Tabbie',
    expense_frequency: 'Once',
    date: '16/12/2021',
    icon: "lipstick",
    time: '2:56 AM',
  },
  {
    id: 36,
    expense_title: 'Aerojet Rocketdyne Holdings, Inc. ',
    expense_category: 'Sports',
    expense_value: '$21747.70',
    expense_owner: 'Amy',
    expense_frequency: 'Yearly',
    date: '18/2/2022',
    icon: "basketball",
    time: '3:16 PM',
  },
  {
    id: 37,
    expense_title: 'Netflix, Inc.',
    expense_category: 'Jewelry',
    expense_value: '$59459.53',
    expense_owner: 'Berny',
    expense_frequency: 'Weekly',
    date: '4/5/2021',
    icon: "diamond-stone",
    time: '9:22 PM',
  },
  {
    id: 38,
    expense_title: 'Pacific Special Acquisition Corp.',
    expense_category: 'Music',
    expense_value: '$4625.27',
    expense_owner: 'Gabriello',
    expense_frequency: 'Once',
    date: '21/6/2021',
    icon: "music-clef-treble",
    time: '1:37 AM',
  },
  {
    id: 39,
    expense_title: 'GTx, Inc.',
    expense_category: 'Home',
    expense_value: '$68893.61',
    expense_owner: 'Archibald',
    expense_frequency: 'Monthly',
    date: '16/8/2021',
    icon: "home-automation",
    time: '7:13 AM',
  },
  {
    id: 40,
    expense_title: 'Ares Capital Corporation',
    expense_category: 'Games',
    expense_value: '$85916.30',
    expense_owner: 'Lyda',
    expense_frequency: 'Never',
    date: '16/5/2021',
    icon: "gamepad-outline",
    time: '4:41 PM',
  },
  {
    id: 41,
    expense_title: 'Bank of Commerce Holdings (CA)',
    expense_category: 'Music',
    expense_value: '$54114.98',
    expense_owner: 'Lauraine',
    expense_frequency: 'Yearly',
    date: '13/11/2021',
    icon: "music-clef-treble",
    time: '10:13 AM',
  },
  {
    id: 42,
    expense_title: 'Suburban Propane Partners, L.P.',
    expense_category: 'Tools',
    expense_value: '$35159.81',
    expense_owner: 'Lari',
    expense_frequency: 'Daily',
    date: '12/5/2021',
    icon: "tools",
    time: '6:09 PM',
  },
  {
    id: 43,
    expense_title: 'Entegris, Inc.',
    expense_category: 'Electronics',
    expense_value: '$37770.84',
    expense_owner: 'Red',
    expense_frequency: 'Monthly',
    date: '22/4/2021',
    icon: "devices",
    time: '3:42 PM',
  },
  {
    id: 44,
    expense_title: 'Rush Enterprises, Inc.',
    expense_category: 'Books',
    expense_value: '$20143.93',
    expense_owner: 'Dimitry',
    expense_frequency: 'Seldom',
    date: '29/9/2021',
    icon: "book-open-page-variant",
    time: '10:04 AM',
  },
  {
    id: 45,
    expense_title: 'Workiva Inc.',
    expense_category: 'Computers',
    expense_value: '$99829.94',
    expense_owner: 'Emera',
    expense_frequency: 'Once',
    date: '31/3/2021',
    icon: "laptop",
    time: '2:20 PM',
  },
  {
    id: 46,
    expense_title: 'AmTrust Financial Services, Inc.',
    expense_category: 'Games',
    expense_value: '$59777.95',
    expense_owner: 'Rodrick',
    expense_frequency: 'Once',
    date: '2/7/2021',
    icon: "gamepad-outline",
    time: '9:08 PM',
  },
  {
    id: 47,
    expense_title: 'SVB Financial Group',
    expense_category: 'Tools',
    expense_value: '$22497.63',
    expense_owner: 'Nealy',
    expense_frequency: 'Weekly',
    date: '2/9/2021',
    icon: "tools",
    time: '9:23 AM',
  },
  {
    id: 48,
    expense_title: "McDonald's Corporation",
    expense_category: 'Health',
    expense_value: '$8762.38',
    expense_owner: 'Benoit',
    expense_frequency: 'Yearly',
    date: '17/3/2022',
    icon: "hospital-box-outline",
    time: '2:42 AM',
  },
  {
    id: 49,
    expense_title: 'Goldman Sachs MLP Energy Renaissance Fund',
    expense_category: 'Home',
    expense_value: '$18807.00',
    expense_owner: 'Trista',
    expense_frequency: 'Yearly',
    date: '6/1/2022',
    icon: "home-automation",
    time: '1:50 AM',
  },
  {
    id: 50,
    expense_title: 'Alphabet Inc.',
    expense_category: 'Electronics',
    expense_value: '$97900.41',
    expense_owner: 'Fulton',
    expense_frequency: 'Once',
    date: '29/3/2021',
    icon: "devices",
    time: '3:58 PM',
  },
  {
    id: 51,
    expense_title: 'argenx SE',
    expense_category: 'Baby',
    expense_value: '$22959.58',
    expense_owner: 'Napoleon',
    expense_frequency: 'Daily',
    date: '9/4/2021',
    icon: "baby-carriage",
    time: '5:55 PM',
  },
  {
    id: 52,
    expense_title: 'Eaton Vance NextShares Trust II',
    expense_category: 'Grocery',
    expense_value: '$27721.96',
    expense_owner: 'Arden',
    expense_frequency: 'Daily',
    date: '23/4/2021',
    icon: "cart",
    time: '10:49 AM',
  },
  {
    id: 53,
    expense_title: 'Saratoga Investment Corp',
    expense_category: 'Industrial',
    expense_value: '$74016.82',
    expense_owner: 'Tye',
    expense_frequency: 'Weekly',
    date: '12/3/2022',
    icon: "cog",
    time: '2:42 AM',
  },
  {
    id: 54,
    expense_title: 'TerraForm Power, Inc.',
    expense_category: 'Clothing',
    expense_value: '$69901.88',
    expense_owner: 'Allx',
    expense_frequency: 'Never',
    date: '16/4/2021',
    icon: "hanger",
    time: '8:07 PM',
  },
  {
    id: 55,
    expense_title: 'GP Investments Acquisition Corp.',
    expense_category: 'Baby',
    expense_value: '$26466.35',
    expense_owner: 'Darell',
    expense_frequency: 'Seldom',
    date: '17/1/2022',
    icon: "baby-carriage",
    time: '6:01 PM',
  },
  {
    id: 56,
    expense_title: 'Chesapeake Energy Corporation',
    expense_category: 'Music',
    expense_value: '$42742.12',
    expense_owner: 'Martha',
    expense_frequency: 'Never',
    date: '2/9/2021',
    icon: "music-clef-treble",
    time: '9:05 PM',
  },
  {
    id: 57,
    expense_title: 'Timken Steel Corporation',
    expense_category: 'Garden',
    expense_value: '$86921.46',
    expense_owner: 'Brett',
    expense_frequency: 'Once',
    date: '9/2/2022',
    icon: "sprout",
    time: '6:03 PM',
  },
  {
    id: 58,
    expense_title: 'Vera Bradley, Inc.',
    expense_category: 'Home',
    expense_value: '$41644.11',
    expense_owner: 'Lianne',
    expense_frequency: 'Monthly',
    date: '15/1/2022',
    icon: "home-automation",
    time: '1:47 PM',
  },
  {
    id: 59,
    expense_title: 'Belden Inc',
    expense_category: 'Toys',
    expense_value: '$31973.60',
    expense_owner: 'Jamil',
    expense_frequency: 'Monthly',
    date: '7/2/2022',
    icon: "pinwheel",
    time: '7:43 AM',
  },
  {
    id: 60,
    expense_title: 'Electro Scientific Industries, Inc.',
    expense_category: 'Books',
    expense_value: '$85578.10',
    expense_owner: 'Berenice',
    expense_frequency: 'Monthly',
    date: '27/3/2021',
    icon: "book-open-page-variant",
    time: '6:10 AM',
  },
  {
    id: 61,
    expense_title: 'Jabil Inc.',
    expense_category: 'Automotive',
    expense_value: '$37713.02',
    expense_owner: 'Bard',
    expense_frequency: 'Often',
    date: '25/2/2022',
    icon: "car",
    time: '8:29 PM',
  },
  {
    id: 62,
    expense_title: 'Capitol Acquisition Corp. III',
    expense_category: 'Tools',
    expense_value: '$68192.58',
    expense_owner: 'Alis',
    expense_frequency: 'Yearly',
    date: '28/7/2021',
    icon: "tools",
    time: '2:20 PM',
  },
  {
    id: 63,
    expense_title: 'Bunge Limited',
    expense_category: 'Shoes',
    expense_value: '$92915.13',
    expense_owner: 'Kristan',
    expense_frequency: 'Daily',
    date: '25/5/2021',
    icon: "shoe-sneaker",
    time: '4:54 PM',
  },
  {
    id: 64,
    expense_title: 'Stratus Properties Inc.',
    expense_category: 'Home',
    expense_value: '$95206.75',
    expense_owner: 'Pavla',
    expense_frequency: 'Seldom',
    date: '19/12/2021',
    icon: "home-automation",
    time: '9:38 AM',
  },
  {
    id: 65,
    expense_title:
      'First Trust International Multi-Asset Diversified Income Index',
    expense_category: 'Music',
    expense_value: '$81457.93',
    expense_owner: 'Mari',
    expense_frequency: 'Never',
    date: '28/5/2021',
    icon: "music-clef-treble",
    time: '11:50 AM',
  },
  {
    id: 66,
    expense_title: 'Ply Gem Holdings, Inc.',
    expense_category: 'Beauty',
    expense_value: '$6768.94',
    expense_owner: 'Byrle',
    expense_frequency: 'Yearly',
    date: '30/8/2021',
    icon: "lipstick",
    time: '6:42 AM',
  },
  {
    id: 67,
    expense_title: 'Regions Financial Corporation',
    expense_category: 'Tools',
    expense_value: '$43546.23',
    expense_owner: 'Lesly',
    expense_frequency: 'Never',
    date: '3/11/2021',
    icon: "tools",
    time: '8:24 AM',
  },
  {
    id: 68,
    expense_title: 'Hess Midstream Partners LP',
    expense_category: 'Beauty',
    expense_value: '$1193.20',
    expense_owner: 'Jeremiah',
    expense_frequency: 'Seldom',
    date: '16/6/2021',
    icon: "lipstick",
    time: '10:05 PM',
  },
  {
    id: 69,
    expense_title: 'Second Sight Medical Products, Inc.',
    expense_category: 'Movies',
    expense_value: '$15074.98',
    expense_owner: 'Constantia',
    expense_frequency: 'Monthly',
    date: '24/1/2022',
    icon: "movie-roll",
    time: '1:03 PM',
  },
  {
    id: 70,
    expense_title: 'Bank of Marin Bancorp',
    expense_category: 'Movies',
    expense_value: '$76042.41',
    expense_owner: 'Dana',
    expense_frequency: 'Weekly',
    date: '15/11/2021',
    icon: "movie-roll",
    time: '1:01 PM',
  },
  {
    id: 71,
    expense_title: 'Morgan Stanley India Investment Fund, Inc.',
    expense_category: 'Grocery',
    expense_value: '$94093.26',
    expense_owner: 'Joachim',
    expense_frequency: 'Never',
    date: '25/5/2021',
    icon: "cart",
    time: '10:16 PM',
  },
  {
    id: 72,
    expense_title: 'Origo Acquisition Corporation',
    expense_category: 'Tools',
    expense_value: '$2695.48',
    expense_owner: 'Elnora',
    expense_frequency: 'Weekly',
    date: '12/2/2022',
    icon: "tools",
    time: '2:56 PM',
  },
  {
    id: 73,
    expense_title: 'Viad Corp',
    expense_category: 'Sports',
    expense_value: '$79527.38',
    expense_owner: 'Noam',
    expense_frequency: 'Weekly',
    date: '2/9/2021',
    icon: "basketball",
    time: '6:28 PM',
  },
  {
    id: 74,
    expense_title: 'Arbor Realty Trust',
    expense_category: 'Music',
    expense_value: '$72558.23',
    expense_owner: 'Adolpho',
    expense_frequency: 'Daily',
    date: '29/4/2021',
    icon: "music-clef-treble",
    time: '8:02 PM',
  },
  {
    id: 75,
    expense_title: 'Centrais Electricas Brasileiras S.A.- Eletrobras',
    expense_category: 'Sports',
    expense_value: '$53041.50',
    expense_owner: 'Rosella',
    expense_frequency: 'Daily',
    date: '11/6/2021',
    icon: "basketball",
    time: '7:47 AM',
  },
  {
    id: 76,
    expense_title: 'Coastway Bancorp, Inc.',
    expense_category: 'Home',
    expense_value: '$5610.90',
    expense_owner: 'Danny',
    expense_frequency: 'Once',
    date: '5/3/2022',
    icon: "home-automation",
    time: '7:53 PM',
  },
  {
    id: 77,
    expense_title: 'Check-Cap Ltd.',
    expense_category: 'Home',
    expense_value: '$95959.98',
    expense_owner: 'Andrej',
    expense_frequency: 'Seldom',
    date: '10/12/2021',
    icon: "home-automation",
    time: '8:28 AM',
  },
  {
    id: 78,
    expense_title: 'American Railcar Industries, Inc.',
    expense_category: 'Clothing',
    expense_value: '$65968.67',
    expense_owner: 'Cherilynn',
    expense_frequency: 'Once',
    date: '31/3/2021',
    icon: "hanger",
    time: '7:58 PM',
  },
  {
    id: 79,
    expense_title: 'The Middleby Corporation',
    expense_category: 'Home',
    expense_value: '$8838.90',
    expense_owner: 'Jemmie',
    expense_frequency: 'Monthly',
    date: '15/6/2021',
    icon: "home-automation",
    time: '9:55 AM',
  },
  {
    id: 80,
    expense_title: 'BB&T Corporation',
    expense_category: 'Computers',
    expense_value: '$5873.37',
    expense_owner: 'Lars',
    expense_frequency: 'Once',
    date: '15/11/2021',
    icon: "laptop",
    time: '1:39 PM',
  },
  {
    id: 81,
    expense_title: 'MediWound Ltd.',
    expense_category: 'Movies',
    expense_value: '$78619.62',
    expense_owner: 'Kleon',
    expense_frequency: 'Daily',
    date: '15/7/2021',
    icon: "movie-roll",
    time: '4:05 AM',
  },
  {
    id: 82,
    expense_title: 'NICE Ltd',
    expense_category: 'Sports',
    expense_value: '$24039.58',
    expense_owner: 'Rosabella',
    expense_frequency: 'Often',
    date: '18/6/2021',
    icon: "basketball",
    time: '9:15 PM',
  },
  {
    id: 83,
    expense_title: 'Double Eagle Acquisition Corp.',
    expense_category: 'Movies',
    expense_value: '$45735.43',
    expense_owner: 'Issi',
    expense_frequency: 'Seldom',
    date: '28/7/2021',
    icon: "movie-roll",
    time: '5:20 AM',
  },
  {
    id: 84,
    expense_title: 'Stone Harbor Emerging Markets Total Income Fund',
    expense_category: 'Health',
    expense_value: '$27045.59',
    expense_owner: 'Welbie',
    expense_frequency: 'Monthly',
    date: '30/9/2021',
    icon: "hospital-box-outline",
    time: '8:21 AM',
  },
  {
    id: 85,
    expense_title: 'Old Line Bancshares, Inc.',
    expense_category: 'Health',
    expense_value: '$25167.33',
    expense_owner: 'Wandie',
    expense_frequency: 'Seldom',
    date: '21/12/2021',
    icon: "hospital-box-outline",
    time: '2:43 AM',
  },
  {
    id: 86,
    expense_title: 'Regeneron Pharmaceuticals, Inc.',
    expense_category: 'Outdoors',
    expense_value: '$56643.17',
    expense_owner: 'Michel',
    expense_frequency: 'Monthly',
    date: '7/9/2021',
    icon: "tent",
    time: '5:36 PM',
  },
  {
    id: 87,
    expense_title: 'Insmed, Inc.',
    expense_category: 'Books',
    expense_value: '$2264.69',
    expense_owner: 'Roxy',
    expense_frequency: 'Monthly',
    date: '15/9/2021',
    icon: "book-open-page-variant",
    time: '1:31 PM',
  },
  {
    id: 88,
    expense_title: 'RiverNorth Opportunities Fund, Inc.',
    expense_category: 'Jewelry',
    expense_value: '$7562.92',
    expense_owner: 'Anthony',
    expense_frequency: 'Once',
    date: '4/3/2022',
    icon: "diamond-stone",
    time: '2:38 AM',
  },
  {
    id: 89,
    expense_title: 'CombiMatrix Corporation',
    expense_category: 'Movies',
    expense_value: '$65582.82',
    expense_owner: 'Dur',
    expense_frequency: 'Yearly',
    date: '12/11/2021',
    icon: "movie-roll",
    time: '2:10 PM',
  },
  {
    id: 90,
    expense_title: 'Alexander & Baldwin Holdings, Inc.',
    expense_category: 'Kids',
    expense_value: '$84365.63',
    expense_owner: 'Aguste',
    expense_frequency: 'Seldom',
    date: '9/11/2021',
    icon: "teddy-bear",
    time: '2:01 PM',
  },
  {
    id: 91,
    expense_title: 'Garmin Ltd.',
    expense_category: 'Automotive',
    expense_value: '$11437.28',
    expense_owner: 'Malina',
    expense_frequency: 'Daily',
    date: '9/8/2021',
    icon: "car",
    time: '9:13 AM',
  },
  {
    id: 92,
    expense_title: 'Atossa Genetics Inc.',
    expense_category: 'Books',
    expense_value: '$47524.41',
    expense_owner: 'Carlo',
    expense_frequency: 'Often',
    date: '9/4/2021',
    icon: "book-open-page-variant",
    time: '11:00 AM',
  },
  {
    id: 93,
    expense_title: 'Nam Tai Property Inc.',
    expense_category: 'Baby',
    expense_value: '$47477.28',
    expense_owner: 'Gregoire',
    expense_frequency: 'Daily',
    date: '11/5/2021',
    icon: "baby-carriage",
    time: '4:23 PM',
  },
  {
    id: 94,
    expense_title: 'Qwest Corporation',
    expense_category: 'Outdoors',
    expense_value: '$21117.43',
    expense_owner: 'Knox',
    expense_frequency: 'Never',
    date: '8/3/2022',
    icon: "tent",
    time: '1:35 AM',
  },
  {
    id: 95,
    expense_title: 'ArQule, Inc.',
    expense_category: 'Automotive',
    expense_value: '$8479.59',
    expense_owner: 'Diana',
    expense_frequency: 'Once',
    date: '25/6/2021',
    icon: "car",
    time: '7:56 AM',
  },
  {
    id: 96,
    expense_title: 'OvaScience Inc.',
    expense_category: 'Electronics',
    expense_value: '$33762.76',
    expense_owner: 'Tabitha',
    expense_frequency: 'Daily',
    date: '25/4/2021',
    icon: "devices",
    time: '8:46 PM',
  },
  {
    id: 97,
    expense_title: 'Pure Cycle Corporation',
    expense_category: 'Computers',
    expense_value: '$41637.12',
    expense_owner: 'Trixi',
    expense_frequency: 'Monthly',
    date: '9/1/2022',
    icon: "laptop",
    time: '7:53 PM',
  },
  {
    id: 98,
    expense_title: 'United Community Banks, Inc.',
    expense_category: 'Movies',
    expense_value: '$23229.64',
    expense_owner: 'Herrick',
    expense_frequency: 'Often',
    date: '9/3/2022',
    icon: "movie-roll",
    time: '10:15 AM',
  },
  {
    id: 99,
    expense_title: 'Origo Acquisition Corporation',
    expense_category: 'Toys',
    expense_value: '$35856.18',
    expense_owner: 'Roby',
    expense_frequency: 'Yearly',
    date: '17/1/2022',
    icon: "pinwheel",
    time: '11:32 AM',
  },
  {
    id: 100,
    expense_title: 'Sibanye Gold Limited',
    expense_category: 'Garden',
    expense_value: '$3532.41',
    expense_owner: 'Abran',
    expense_frequency: 'Never',
    date: '10/10/2021',
    icon: "sprout",
    time: '7:19 AM',
  },
];
